---
# branches:
#     only:
#     - master
os: osx
language: node_js
node_js:
    - node
cache: yarn
before_script:
    - yarn global add expo-cli
script:
    - yarn install
    - expo login --non-interactive -u joehoyle
    - export COMMIT=$(git rev-parse HEAD | cut -c1-7)
    - sed -E 's/(buildNumber": ")([^"]+)/\1'$COMMIT'/' app.json
    - expo build:ios --apple-id joehoyle@gmail.com
    - expo upload:ios --apple-id joehoyle@gmail.com --latest
