---
branches:
    only:
    - master
os: osx
osx_image: xcode11.3
git:
    depth: false
language: node_js
node_js:
    - node
cache: yarn
before_script:
    - yarn global add expo-cli
script:
    - yarn install
    - yarn run get-icons
    - expo login --non-interactive -u $EXPO_USERNAME
    - git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
    - git fetch -a
    - export buildNumber=$(git rev-list $( git describe --tags $(git rev-list --tags --max-count=1) )..master --count)
    - echo "Updating build number to $buildNumber using branch 'master'."
    - >
      sed -E 's/(buildNumber": ")([^"]+)/\1'$buildNumber'/' app.json > tmp
    - mv tmp app.json
    - expo build:ios --apple-id $EXPO_APPLE_ID
    - travis_wait 40 expo upload:ios --latest
