---
# branches:
#     only:
#     - master
language: node_js
node_js:
    - node
cache:
    directories:
    - ~/.npm
    - .jest
before_script:
    - yarn global add expo-cli
script:
    - yarn install
    - expo expo login --non-interactive -u joehoyle
    - expo build:ios
